#!/bin/sh

temp_file=$(mktemp)
declare -A timeZones
tmp3=$(mktemp)
timeZones["bruh"]="nice"
line="bruh"

echo "${!timeZones[@]}" > $tmp3
if [ -n "$(grep "$line" $tmp3)" ]; then
        #append to the dict 
        echo "append"
    else   
        #idk
        echo "idk"
fi

rm $tmp3